// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialCare.Infrastructure.Data;

#nullable disable

namespace SocialCare.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602185657_AddIconePrograma")]
    partial class AddIconePrograma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialCare.Domain.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssistenteResponsavelId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Demanda")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Parecer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Remoto")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssistenteResponsavelId");

                    b.HasIndex("DataAtendimento");

                    b.HasIndex("FamiliaId");

                    b.ToTable("atendimento", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Beneficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprovadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoEncerramento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProgramaSocialId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("AprovadoPorUsuarioId");

                    b.HasIndex("ProgramaSocialId");

                    b.HasIndex("FamiliaId", "ProgramaSocialId", "DataInicio");

                    b.ToTable("beneficio", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembroId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.HasIndex("TipoDocumentoId", "Numero");

                    b.ToTable("documento", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Encaminhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEncaminhamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("datetime2");

                    b.Property<string>("Demanda")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<int>("InstituicaoParceiraId")
                        .HasColumnType("int");

                    b.Property<int?>("MembroId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Retorno")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataEncaminhamento");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("InstituicaoParceiraId");

                    b.HasIndex("MembroId");

                    b.ToTable("encaminhamento", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PontoReferencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cep");

                    b.HasIndex("FamiliaId")
                        .IsUnique();

                    b.HasIndex("MunicipioId");

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CodigoIbge")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique();

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoFamiliar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MembroResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuantidadeMembros")
                        .HasColumnType("int");

                    b.Property<decimal>("RendaPerCapita")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RendaTotalMensal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoFamiliar")
                        .IsUnique();

                    b.HasIndex("MembroResponsavelId");

                    b.ToTable("familia", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.FamiliaVulnerabilidade", b =>
                {
                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<int>("VulnerabilidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IdentificadaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Resolvida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvidaEm")
                        .HasColumnType("datetime2");

                    b.HasKey("FamiliaId", "VulnerabilidadeId");

                    b.HasIndex("VulnerabilidadeId");

                    b.ToTable("familia_vulnerabilidade", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.InstituicaoParceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaAtuacao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EnderecoCompleto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ResponsavelContato")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("instituicao_parceira", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntidadeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("log_auditoria", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDeficiencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomePai")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ocupacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParentescoId")
                        .HasColumnType("int");

                    b.Property<bool>("PessoaComDeficiencia")
                        .HasColumnType("bit");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("ParentescoId");

                    b.ToTable("membro", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CodigoIbge")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique();

                    b.HasIndex("EstadoId", "Nome");

                    b.ToTable("municipio", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Parentesco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("parentesco", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Responsável familiar",
                            Nome = "Responsável"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cônjuge"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Filho(a)"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Enteado(a)"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Pai/Mãe"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Avô/Avó"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Neto(a)"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Irmão/Irmã"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Outro"
                        });
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Acesso total ao sistema",
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Programas, benefícios e relatórios",
                            Nome = "Gestor"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Atuação direta com famílias e visitas",
                            Nome = "AssistenteSocial"
                        });
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.ProgramaSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DuracaoMesesPadrao")
                        .HasColumnType("int");

                    b.Property<string>("IconeBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OrgaoResponsavel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Requisitos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("ValorPadrao")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("programa_social", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Transferência de renda para famílias em vulnerabilidade",
                            Nome = "Bolsa Família",
                            OrgaoResponsavel = "MDS"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Auxílio para compra de gás de cozinha",
                            Nome = "Auxílio Gás",
                            OrgaoResponsavel = "MDS"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "BPC - Benefício de Prestação Continuada",
                            OrgaoResponsavel = "INSS"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Programa Leite das Crianças",
                            OrgaoResponsavel = "Secretaria Estadual"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Tarifa Social de Energia",
                            OrgaoResponsavel = "ANEEL"
                        });
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Renda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fonte")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MembroId")
                        .HasColumnType("int");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoRendaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoRendaId");

                    b.HasIndex("MembroId", "AnoReferencia", "MesReferencia");

                    b.ToTable("renda", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("MascaraValidacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("tipo_documento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MascaraValidacao = "###.###.###-##",
                            Nome = "CPF",
                            Sigla = "CPF"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "RG",
                            Sigla = "RG"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Número de Identificação Social",
                            Sigla = "NIS"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Certidão de Nascimento",
                            Sigla = "CertidaoNasc"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Carteira de Trabalho",
                            Sigla = "CTPS"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Título de Eleitor",
                            Sigla = "TituloEleitor"
                        });
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.TipoRenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ConsideradaParaCalculo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tipo_renda", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            ConsideradaParaCalculo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Salário CLT"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            ConsideradaParaCalculo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Autônomo"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            ConsideradaParaCalculo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Aposentadoria"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            ConsideradaParaCalculo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Pensão"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            ConsideradaParaCalculo = false,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Bolsa Família"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            ConsideradaParaCalculo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Benefício de Prestação Continuada"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            ConsideradaParaCalculo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Trabalho Informal"
                        });
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtribuidoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PerfilId");

                    b.HasIndex("PerfilId");

                    b.ToTable("usuario_perfil", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssistenteResponsavelId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Encaminhamentos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssistenteResponsavelId");

                    b.HasIndex("DataAgendada");

                    b.HasIndex("FamiliaId");

                    b.ToTable("visita", (string)null);
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Vulnerabilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Severidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("vulnerabilidade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Insegurança alimentar",
                            Severidade = 3
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Moradia precária",
                            Severidade = 3
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Violência doméstica",
                            Severidade = 4
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Trabalho infantil",
                            Severidade = 4
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Situação de rua",
                            Severidade = 4
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Desemprego prolongado",
                            Severidade = 2
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Evasão escolar",
                            Severidade = 3
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Dependência química",
                            Severidade = 4
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Idoso em situação de risco",
                            Severidade = 4
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Gestante sem acompanhamento",
                            Severidade = 3
                        });
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Usuario", "AssistenteResponsavel")
                        .WithMany("AtendimentosResponsavel")
                        .HasForeignKey("AssistenteResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.Familia", "Familia")
                        .WithMany("Atendimentos")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssistenteResponsavel");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Beneficio", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Usuario", "AprovadoPor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialCare.Domain.Entities.Familia", "Familia")
                        .WithMany("Beneficios")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.ProgramaSocial", "ProgramaSocial")
                        .WithMany("Beneficios")
                        .HasForeignKey("ProgramaSocialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("Familia");

                    b.Navigation("ProgramaSocial");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Documento", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Membro", "Membro")
                        .WithMany("Documentos")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membro");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Encaminhamento", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Familia", "Familia")
                        .WithMany("Encaminhamentos")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.InstituicaoParceira", "InstituicaoParceira")
                        .WithMany("Encaminhamentos")
                        .HasForeignKey("InstituicaoParceiraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Familia");

                    b.Navigation("InstituicaoParceira");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Familia", "Familia")
                        .WithOne("Endereco")
                        .HasForeignKey("SocialCare.Domain.Entities.Endereco", "FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Enderecos")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Familia", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Membro", "MembroResponsavel")
                        .WithMany()
                        .HasForeignKey("MembroResponsavelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MembroResponsavel");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.FamiliaVulnerabilidade", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Familia", "Familia")
                        .WithMany("Vulnerabilidades")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.Vulnerabilidade", "Vulnerabilidade")
                        .WithMany("Familias")
                        .HasForeignKey("VulnerabilidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Vulnerabilidade");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Membro", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Familia", "Familia")
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.Parentesco", "Parentesco")
                        .WithMany("Membros")
                        .HasForeignKey("ParentescoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Parentesco");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Renda", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Membro", "Membro")
                        .WithMany("Rendas")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.TipoRenda", "TipoRenda")
                        .WithMany("Rendas")
                        .HasForeignKey("TipoRendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membro");

                    b.Navigation("TipoRenda");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Perfil", "Perfil")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Visita", b =>
                {
                    b.HasOne("SocialCare.Domain.Entities.Usuario", "AssistenteResponsavel")
                        .WithMany("VisitasResponsavel")
                        .HasForeignKey("AssistenteResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialCare.Domain.Entities.Familia", "Familia")
                        .WithMany("Visitas")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssistenteResponsavel");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Familia", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Beneficios");

                    b.Navigation("Encaminhamentos");

                    b.Navigation("Endereco");

                    b.Navigation("Membros");

                    b.Navigation("Visitas");

                    b.Navigation("Vulnerabilidades");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.InstituicaoParceira", b =>
                {
                    b.Navigation("Encaminhamentos");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Membro", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Rendas");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Parentesco", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("UsuarioPerfis");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.ProgramaSocial", b =>
                {
                    b.Navigation("Beneficios");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.TipoRenda", b =>
                {
                    b.Navigation("Rendas");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AtendimentosResponsavel");

                    b.Navigation("Auditorias");

                    b.Navigation("UsuarioPerfis");

                    b.Navigation("VisitasResponsavel");
                });

            modelBuilder.Entity("SocialCare.Domain.Entities.Vulnerabilidade", b =>
                {
                    b.Navigation("Familias");
                });
#pragma warning restore 612, 618
        }
    }
}
